config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
enum status:  {draft: 0, published: 1}

  extend FriendlyId
friendly_id :title, use: :slugged

has_many :comments, dependent: :destroy

validates_presence_of :title, :body

mount_uploader :thumb_image, BlogUploader


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"

  access all: [:show, :index, :new], user: {except: [:destroy, :create, :update, :edit, :toggle_status]}, site_admin: :all
  # GET /blogs
  # GET /blogs.json
  def index
    @q = Blog.ransack(params[:q])
    @blogs = @q.result(distinct: true).page(params[:page]).per(5).order('created_at DESC')

    # @blogs = Blog.page(params[:page]).per(5).order('created_at DESC')
    # @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.includes(:comments).friendly.find(params[:id])
    @comment = Comment.new
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
      if @blog.draft?
        @blog.published!
      elsif @blog.published?
        @blog.draft!
      end
      redirect_to blogs_url, notice: 'Post status has been updated.'
        end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end


end

app/helpers/blogs_helper.rb
module BlogsHelper
  class CodeRayify < Redcarpet::Render::HTML
   def block_code(code, language)
     CodeRay.scan(code, language).div
   end
 end

 def markdown(text)
   coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

   options = {
     fenced_code_blocks: true,
     no_intra_emphasis: true,
     autolink: true,
     lax_html_blocks: true,
   }

   markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
   markdown_to_html.render(text).html_safe
 end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
  <nav class="breadcrumb blogcrumb">
    <%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog) %>
    <%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure?' } %>
  </nav>
<% end %>

app/views/blogs/_blog.html.erb
<th><%= sort_link(@q, :title) %></th>

<table>
<div class="container index-blog">
  <div class="row justify-center my-row">
    <div class="col-md-10 col-sm-10 my-col">
      <table>


            <div class="titleindex"><%= blog.title %></strong></div
            <%= render partial: 'blogs/admin_actions', locals: { blog: blog } %>
      <p>
            <% if blog.body.length > 350 %>
            <%= truncate( strip_tags(markdown(blog.body)), length: 350) %>
                    <% end %>
      </p>


      <p>
        <%= link_to "READ MORE", blog_path(blog), class: "btn btn-primary" %>
      </p>

          <i class="icon-calendar"></i> <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now)%> ago</p>

        </p>
        <hr>

        <div>
      </div>
    </div>
    </table>

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= f.radio_button :status, 'draft' %>
    <%= f.label :status, 'Draft' %>
     <%= f.radio_button :status, 'published' %>
    <%= f.label :status, 'Published' %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, class: 'form-control', rows: 15, placeholder: "Content" %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>



 <!-- <div class="form-group">
    <label class="btn btn-primary">
      Upload a thumb image file <%= f.file_field :thumb_image, style: 'display:none;' %>
    </label>
  </div>
</div> -->

<% end %>

app/views/blogs/edit.html.erb
 <div class="col-sm-8 blog-main">
   <h1>Editing Blog</h1>

   <%= render 'form', blog: @blog %>

   <%= link_to 'Show', @blog %> |
   <%= link_to 'Back', blogs_path %>
 </div>

app/views/blogs/index.html.erb
<div class = "search-bar">
<%= search_form_for @q  do |f| %>
  <%= f.label :title_or_body_cont,"    KEY WORD  " %>
  <%= f.search_field :title_or_body_cont %>
  <%= f.submit "Search" %>
<% end %>
</div>

<div class = "new-button">
<% if logged_in?(:site_admin) %>
   <p class="blog-post-meta">
  <%= link_to 'New Post', new_blog_path,  class: "btn-warning"%>
  <% end %>
   </p>
   </div>

<div class="col-sm-8 blog-main">
    <%= render @blogs %>
    <%= paginate @blogs %>

</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New Post</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">

<div class=blog-title-show>
  <h2><%= @blog.title %></h2>
</div>


  <nav class="breadcrumb">
    <span class="pull-left">
   <%= link_to "Home", root_path, class: 'breadcrumb-item' %>
   <%= link_to "Back", blogs_path, class: 'breadcrumb-item' %>
   <span class="breadcrumb-item active"><%= @blog.title %></span>
</spam>



     <%= link_to fa_icon('pencil-square-o'), edit_blog_path(@blog) if logged_in?(:site_admin) %>
     <%= link_to fa_icon('trash'), @blog, method: :delete, data: { confirm: 'Are you sure you want to delete this post' } if logged_in?(:site_admin) %>

 </nav>

  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %>

  <p>
    <%= markdown @blog.body %>
  </p>

  <%= render 'comments/comment_form' %>
  <hr>
<h5>COMMENTS:</h5>
  <div class"comment">
  <div id="comments" data-blog-id="<%= @blog.id %>">
     <%= render @blog.comments %>
   </div>
 </div>
</div>