config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="text-muted">
  <div class="container">

    <%=  set_copyright  %>
    </p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<nav class="navbar navbar-expand  navbar-dark sticky-top" style="background-color: #384452;">

  


    <ul class="navbar-nav ml-auto">

      <li class="nav-item"><%= link_to "Home", root_path , class: 'nav-link'%></li>
      <li class="nav-item"><%= link_to "About", about_me_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "Contact", contact_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "Posts", blogs_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "Projects", portfolios_path, class: 'nav-link' %></li>
      <%= login_helper 'nav-link' %>
    </ul>
  </nav>

app/views/shared/_blog_footer.html.erb
<footer class="text-muted">
  <div class="container">
<div class="backtop">
    <p class="float-right">
      <a href="#", class: "a-primary">Back to top</a>
    </p>
  </div>


    <%=  set_copyright  %>
  </div>
  </div>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div id="blue">
  <div class="container">
    <div class="row">
      <h3>POSTS</h3>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand nav-justified  navbar-dark sticky-top" style="background-color: #384452;">

  <h3 class="navbar-brand"  >AMBALA JATTAN</h3>


    <ul class="navbar-nav ml-auto">

      <li class="nav-item"><%= link_to "Home", root_path , class: 'nav-link'%></li>
      <li class="nav-item"><%= link_to "About", about_me_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "Contact", contact_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "Posts", blogs_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "Projects", portfolios_path, class: 'nav-link' %></li>
      <%= login_helper 'nav-link' %>
    </ul>
  </nav>

app/views/shared/_blog_sidebar.html.erb
<div>
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</div>
</div>

app/views/shared/_nav.html.erb
<div class= "<%=location %>"
    <div>
<%= link_to "Home", root_path %>
<%= link_to "About-Us", about_me_path %>
<%= link_to "Contact", contact_path %>
<%= link_to "Blog", blogs_path %>
<%= link_to "Portfolio", portfolios_path %>

  </div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
<div class="backtop">
    <p class="float-right">
      <a href="#", class: "a-primary">Back to top</a>
    </p>
  </div>


    <%=  set_copyright  %>

  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<div class="blog-header">
  <div id="blue">
  <div class="container">
    <div class="row">
      <h3>PROJECTS</h3>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
  </div>
</div>

app/views/shared/_portfolio_nav.html.erb
 <!--- <body>
<nav class="navbar navbar-expand-lg   navbar-dark bg-dark">
 <div class="container">
  <h3 class="navbar-brand">AMBALA JATTAN</h3>


  <button class="navbar-toggler" type="button" data-toggle="collapse"
  data-target="#navbarResponsive" aria-controls="navbarResponsive"
  aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

    <div class="collapse navbar-collapse id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
            <%= link_to "Home", root_path , class: 'nav-link'%>
              <span class="sr-only">(current)</span>
            </li>
              <li class="nav-item active">
                <%= link_to "About", about_me_path, class: 'nav-link' %>
                </li>
                <li class="nav-item active">
                    <%= link_to "Contact", contact_path, class: 'nav-link' %>
                    </li>

                  <li class="nav-item active">
                        <%= link_to "Posts", blogs_path, class: 'nav-link' %>
                  </li>
                  <li class="nav-item active">
                        <%= link_to "Projects", portfolios_path, class: 'nav-link' %>
                    </li>
                    <%= login_helper 'nav-link' %>

    </ul>

  </nav>
</div>
</body>-->


  <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: #384452;">
    <div class="container">
      <div class="navbar-brand" >Ambala Jattan</div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path , class: 'nav-link'%>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <%= link_to "About", about_me_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to "Contact", contact_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
          <%= link_to "Posts", blogs_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Projects", portfolios_path, class: 'nav-link' %>
          </li>

            <%= login_helper 'nav-link' %>

        </ul>
      </div>
    </div>
  </nav>